---
title: "Call for Climate Doers and Thinkers"
#image: 
page-layout: full
---

Hi there! My name is [Gang He](https://drganghe.github.io), and I'm an Assistant Professor of Energy and Climate Policy in the Marxe School of Public and International Affairs at Baruch College, City University of New York. I’m excited to be teaching the [Energy and Climate Policy](https://drganghe.github.io/energy-climate-policy/) graduate class in the Fall semester and the [Energy, Climate, and Society](https://drganghe.github.io/energy-climate-society/) undergraduate class in the Spring semester, both on Monday evenings. I’m seeking guest speakers who are passionate about sharing their experiences and inspiring next generation of climate leaders.

We’re exploring the following key themes:

- **Climate and Career**: Share your journey working in climate-focused roles, discussing what led you to this path and how your work contributes to meaningful climate solutions.
- **Climate and Community**: Highlight impactful activities that bring climate actions to the community level, showcasing the power of local engagement.
- **Climate New Research**: We always welcome exciting new research, so if you have fresh insights or innovative projects, we’d love to hear from you.
- **Climate Nexus**: Share your perspective and experiences on the intersection between climate and energy, environment, industry, market, governance, and explore  interdisciplinary approaches to climate policy.

Here is how it works:

- **What you’ll provide**: A 30-minute virtual sharing session plus Q&A.
- **What you’ll get**: A highlight on our course webpage and the opportunity to influence and possibly change the career paths of our students.

If interested, please fill out a quick expression of interest [form](https://forms.gle/AD4pujkhQkGiUHT69), or reach out to me by [email](mailto:gang.he@baruch.cuny.edu) or [messages](https://www.linkedin.com/in/hegang) with your ideas, and the students will decide which topics aligns with their interests. We are particularly interested in hearing earlier career professionals and those doing hands-on work in the field.

Let’s collaborate to empower and inspire the climate leaders of tomorrow. 